# Generated by Django 3.2.9 on 2022-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20220204_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-02-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
